---
- name: Disable systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    enabled: False
    state: stopped
  tags: chrony

- name: Install Chrony
  apt:
    name: chrony
    state: present
    update_cache: True
    cache_valid_time: 3600
  tags: chrony

- name: Configure Chrony
  template:
    dest: /etc/chrony/chrony.conf
    src: chrony.conf.j2
    owner: root
    group: root
    mode: '644'
  notify: restart chrony
  tags: chrony

- name: Flush handlers
  meta: flush_handlers
  tags: chrony

- name: Start and enable chronyd
  systemd:
    name: chrony
    enabled: True
    state: started
  tags: chrony
